function []=pcn_plotsepline(inputs, targets, weights)
    axis ([-2, 2, -2, 2], 'square');
    p = weights(1,1:2);
    k = -weights(1, size(inputs, 1)) / (p*p');
    l = sqrt(p*p');
    plot (inputs(1, find(targets>0)), ...
    inputs(2, find(targets>0)), '*', ...
    inputs(1, find(targets<0)), ...
    inputs(2, find(targets<0)), '+', ...
    [p(1), p(1)]*k + [-p(2), p(2)]/l, ...
    [p(2), p(2)]*k + [p(1), -p(1)]/l, '-');
    drawnow;
end

